port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 50200
  use_external_ip: false
  
redis:
  address: redis:6379
  
keys:
  devkey: devsecret
  
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 10
  
logging:
  level: info
  sample: false
